"use client";

import type { ColumnDef } from "@tanstack/react-table";
import { RiArrowDownLine, RiArrowUpLine, RiFocus3Line, RiShieldCheckLine } from "react-icons/ri";
import type { AllocationEntry, AllocationRule, AppSettings, Asset, GoalFund, IncomeEvent, InvestmentTransaction, MarketQuote, PlanItem } from "@/lib/types";
import { useReportsData, type PerformanceRow, type PlanAdherenceRow } from "@/hooks/use-reports-data";
import { formatMoney, formatPercent } from "@/lib/format";
import { cn } from "@/lib/utils";
import { DataTable, type DataTableFeatures } from "@/components/data-table";
import { AllocationDonut } from "@/components/charts/allocation-donut";
import { MonthlyBars } from "@/components/charts/monthly-bars";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";


export function ReportsSection({ settings, rule, incomes, allocations, funds, assets, transactions, quotes, planItems }: { settings:AppSettings; rule?:AllocationRule; incomes:IncomeEvent[]; allocations:AllocationEntry[]; funds:GoalFund[]; assets:Asset[]; transactions:InvestmentTransaction[]; quotes:MarketQuote[]; planItems:PlanItem[] }) {
  const report = useReportsData({ incomes, allocations, funds, assets, transactions, quotes, planItems });
  const { performance: perf, totalIncome, totals, funded, target, best, worst, monthly, overallPlan, planRows } = report;
  const planColumns:ColumnDef<DataTableFeatures,PlanAdherenceRow,unknown>[]=[
    {accessorKey:"title",header:"\u067e\u0648\u0644 \u0648\u0631\u0648\u062f\u06cc",cell:({row})=><strong>{row.original.title}</strong>},
    {accessorKey:"planned",header:"\u0628\u0631\u0646\u0627\u0645\u0647",cell:({row})=>formatMoney(row.original.planned,settings.displayUnit)},
    {accessorKey:"executed",header:"\u0627\u062c\u0631\u0627\u0634\u062f\u0647",cell:({row})=>formatMoney(row.original.executed,settings.displayUnit)},
    {accessorKey:"pct",header:"\u067e\u0627\u06cc\u0628\u0646\u062f\u06cc",cell:({row})=><strong className={row.original.pct>=90?"text-primary":row.original.pct<50?"text-destructive":""}>{formatPercent(row.original.pct,0)}</strong>},
  ];
  const columns:ColumnDef<DataTableFeatures,PerformanceRow,unknown>[]=[
    {accessorKey:"name",header:"دارایی",cell:({row})=><strong>{row.original.name}</strong>},
    {accessorKey:"value",header:"ارزش",cell:({row})=>formatMoney(row.original.value,settings.displayUnit)},
    {accessorKey:"target",header:"هدف",cell:({row})=>formatPercent(row.original.target,0)},
    {accessorKey:"actual",header:"واقعی",cell:({row})=>formatPercent(row.original.actual,1)},
    {id:"drift",header:"انحراف",cell:({row})=>{const d=row.original.actual-row.original.target;return <span className={cn("font-bold",Math.abs(d)>8?"text-destructive":"text-muted-foreground")}>{d>=0?"+":""}{formatPercent(d,1)}</span>}},
    {accessorKey:"pnlPct",header:"بازده",cell:({row})=><div className={cn("font-bold",row.original.pnlPct>=0?"text-primary":"text-destructive")}>{row.original.pnlPct>=0?"+":""}{formatPercent(row.original.pnlPct)}<div className="text-[10px] font-normal">{formatMoney(row.original.pnl,settings.displayUnit,true)}</div></div>},
  ];
  return <div className="space-y-5"><div><div className="text-xs font-semibold text-primary">تحلیل</div><h1 className="mt-1 text-2xl font-black sm:text-3xl">گزارش‌ها و بینش‌ها</h1><p className="mt-1 text-sm text-muted-foreground">هدف این صفحه جواب‌دادن به «پولم چطور پخش شده و تصمیم‌هایم چه نتیجه‌ای داشته؟» است.</p></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><InsightCard icon={<RiFocus3Line/>} label="کل پول ورودی" value={formatMoney(totalIncome,settings.displayUnit)} detail={`${new Intl.NumberFormat("fa-IR").format(incomes.length)} ورودی ثبت‌شده`}/><InsightCard icon={<RiFocus3Line/>} label={"\u067e\u0627\u06cc\u0628\u0646\u062f\u06cc \u0628\u0647 \u0628\u0631\u0646\u0627\u0645\u0647"} value={formatPercent(overallPlan.pct,0)} detail={`${formatMoney(overallPlan.executed,settings.displayUnit,true)} / ${formatMoney(overallPlan.planned,settings.displayUnit,true)}`}/><InsightCard icon={<RiShieldCheckLine/>} label="پوشش صندوق‌ها" value={formatPercent(target?funded/target*100:0,0)} detail={`${formatMoney(funded,settings.displayUnit,true)} ذخیره شده`}/><InsightCard icon={<RiArrowUpLine/>} label="بهترین بازده" value={best?`${best.name} ${formatPercent(best.pnlPct)}`:"—"} detail={best?formatMoney(best.pnl,settings.displayUnit,true):"هنوز داده کافی نیست"} positive/><InsightCard icon={<RiArrowDownLine/>} label="ضعیف‌ترین بازده" value={worst?`${worst.name} ${formatPercent(worst.pnlPct)}`:"—"} detail={worst?formatMoney(worst.pnl,settings.displayUnit,true):"هنوز داده کافی نیست"} positive={worst?.pnlPct!==undefined?worst.pnlPct>=0:undefined}/></div>
  <div className="grid gap-4 xl:grid-cols-[.9fr_2.1fr]"><Card><CardHeader><CardTitle>تقسیم تاریخی پول</CardTitle></CardHeader><CardContent><div className="grid place-items-center"><AllocationDonut segments={[{label:"زندگی",value:totalIncome?totals.life/totalIncome*100:(rule?.lifePct??30)},{label:"امنیت",value:totalIncome?totals.safety/totalIncome*100:(rule?.safetyPct??20)},{label:"رشد",value:totalIncome?totals.growth/totalIncome*100:(rule?.growthPct??50)}]}/></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><Legend color="var(--chart-3)" label="زندگی" value={totalIncome?totals.life/totalIncome*100:(rule?.lifePct??30)}/><Legend color="var(--chart-2)" label="امنیت" value={totalIncome?totals.safety/totalIncome*100:(rule?.safetyPct??20)}/><Legend color="var(--chart-1)" label="رشد" value={totalIncome?totals.growth/totalIncome*100:(rule?.growthPct??50)}/></div></CardContent></Card><Card><CardHeader><CardTitle>تقسیم ماهانه</CardTitle></CardHeader><CardContent><MonthlyBars data={monthly} unit={settings.displayUnit}/></CardContent></Card></div>
  <Card><CardHeader><CardTitle>{"\u067e\u0627\u06cc\u0628\u0646\u062f\u06cc \u0628\u0647 \u0628\u0631\u0646\u0627\u0645\u0647\u200c\u0647\u0627\u06cc \u067e\u0648\u0644 \u0648\u0631\u0648\u062f\u06cc"}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{"\u067e\u06cc\u0634\u0646\u0647\u0627\u062f \u067e\u0648\u0644\u200c\u06cc\u0627\u0631 \u0628\u0627 \u0622\u0646\u0686\u0647 \u0648\u0627\u0642\u0639\u0627\u064b \u0627\u062c\u0631\u0627 \u06a9\u0631\u062f\u0647\u200c\u0627\u06cc \u0645\u0642\u0627\u06cc\u0633\u0647 \u0645\u06cc\u200c\u0634\u0648\u062f."}</p></CardHeader><CardContent><DataTable<PlanAdherenceRow> data={planRows} columns={planColumns} searchPlaceholder={"\u062c\u0633\u062a\u200c\u0648\u062c\u0648\u06cc \u0628\u0631\u0646\u0627\u0645\u0647..."} mobileCard={(row)=><div className="p-4"><div className="flex items-start justify-between"><strong>{row.title}</strong><span className="font-black text-primary">{formatPercent(row.pct,0)}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><Small label={"\u0628\u0631\u0646\u0627\u0645\u0647"} value={formatMoney(row.planned,settings.displayUnit,true)}/><Small label={"\u0627\u062c\u0631\u0627\u0634\u062f\u0647"} value={formatMoney(row.executed,settings.displayUnit,true)}/></div></div>} /></CardContent></Card>
  <Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>تخصیص هدف در برابر واقعیت</CardTitle><p className="mt-1 text-xs text-muted-foreground">اگر یک دارایی از هدف دور شده، پول جدید می‌تواند اول به دارایی‌های کم‌وزن‌تر برود.</p></div><Badge>Rebalance با پول جدید</Badge></CardHeader><CardContent><DataTable<PerformanceRow> data={perf} columns={columns} searchPlaceholder="جست‌وجوی دارایی..." mobileCard={(row)=><div className="p-4"><div className="flex items-start justify-between"><div><div className="font-bold">{row.name}</div><div className="mt-1 text-xs text-muted-foreground">ارزش {formatMoney(row.value,settings.displayUnit)}</div></div><div className={cn("font-black",row.pnlPct>=0?"text-primary":"text-destructive")}>{row.pnlPct>=0?"+":""}{formatPercent(row.pnlPct)}</div></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><Small label="هدف" value={formatPercent(row.target,0)}/><Small label="واقعی" value={formatPercent(row.actual,1)}/><Small label="انحراف" value={`${row.actual-row.target>=0?"+":""}${formatPercent(row.actual-row.target,1)}`}/></div></div>} /></CardContent></Card>
  </div>;
}
function InsightCard({icon,label,value,detail,positive}:{icon:React.ReactNode;label:string;value:string;detail:string;positive?:boolean}){return <Card><CardContent className="p-4"><div className="flex justify-between"><div><div className="text-xs text-muted-foreground">{label}</div><div className={cn("mt-2 text-lg font-black",positive!==undefined&&(positive?"text-primary":"text-destructive"))}>{value}</div><div className="mt-1 text-[10px] text-muted-foreground">{detail}</div></div><div className="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary [&_svg]:size-5">{icon}</div></div></CardContent></Card>}
function Legend({label,value,color}:{label:string;value:number;color:string}){return <div className="rounded-xl bg-muted/50 p-2"><div className="flex items-center justify-center gap-1.5"><span className="size-2.5 rounded-full" style={{backgroundColor:color}}/><div className="font-black">{formatPercent(value,0)}</div></div><div className="mt-1 text-[10px] text-muted-foreground">{label}</div></div>}
function Small({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-muted/50 p-2"><div className="font-bold">{value}</div><div className="mt-1 text-[10px] text-muted-foreground">{label}</div></div>}
