"use client";

import Link from "next/link";
import { RiFundsLine, RiSafe2Line } from "react-icons/ri";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { buttonStyles } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { SensitiveValue } from "@/components/ui/sensitive-value";
import { formatMoney, formatPercent, formatSignedMoney } from "@/lib/format";
import { equivalentLossBudget } from "@/lib/loans/calculations";
import type { LoanView } from "@/lib/loans/analytics";
import type { AppSettings } from "@/lib/types";
import { cn } from "@/lib/utils";

export function LoanCapital({ view, settings, onConnectAsset }: { view: LoanView; settings: AppSettings; onConnectAsset?: (asset: LoanView["positions"][number]["asset"]) => void }) {
  const budget = view.loan.riskBudgetInstallments ? equivalentLossBudget(view.installmentToman, view.loan.riskBudgetInstallments) : 0;
  const availablePositions = view.positions.filter((position) => position.status === "available");
  return <div className="space-y-4"><Card><CardHeader><CardTitle>وجه نقد متصل به وام</CardTitle></CardHeader><CardContent><div className="type-caption text-muted-foreground">مبلغ دریافتی منهای هزینه اولیه، تامین ذخیره از وام، خریدها و پرداخت‌های انجام‌شده از فروش دارایی.</div><SensitiveValue className="mt-2 block type-section-title">{formatMoney(view.loanCashToman, settings.displayUnit)}</SensitiveValue>{view.fundingGapToman > 0.5 && <div className="mt-3 rounded-xl border border-destructive/25 bg-destructive/8 p-3 type-caption text-destructive">منابع ثبت‌شده برای خریدهای متصل حدود {formatMoney(view.fundingGapToman, settings.displayUnit, true)} کسری دارند. این اختلاف به‌صورت محافظه‌کارانه آورده شخصی محاسبه شده است.</div>}</CardContent></Card><Card><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>ذخیره بازپرداخت</CardTitle><p className="mt-1 type-caption text-muted-foreground">پوشش فعلی فقط از موجودی امروز محاسبه می‌شود، نه سود آینده.</p></div><Link href="/funds" className={buttonStyles({ variant: "outline", size: "sm" })}><RiSafe2Line /> صندوق‌ها</Link></div></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-[1fr_1fr]"><div><div className="type-caption text-muted-foreground">موجودی فعلی</div><SensitiveValue className="mt-1 block type-section-title">{formatMoney(view.reserveBalanceToman, settings.displayUnit)}</SensitiveValue><div className="mt-1 type-caption text-muted-foreground">معادل {view.reserveRunwayMonths.toLocaleString("fa-IR", { maximumFractionDigits: 1 })} قسط</div></div><div><div className="flex justify-between type-caption"><span>پیشرفت تا هدف</span><span>{formatPercent(view.reserveProgressPct, 0)}</span></div><Progress value={view.reserveProgressPct} className="mt-2"/><div className="mt-2 type-caption text-muted-foreground">هدف {formatMoney(view.reserveTargetToman, settings.displayUnit, true)} · {view.loan.reserveTargetMonths.toLocaleString("fa-IR")} قسط</div></div></div></CardContent></Card>
  <Card><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>دارایی‌های متصل به وام</CardTitle><p className="mt-1 type-caption text-muted-foreground">فقط تراکنش‌هایی که منبعشان همین وام ثبت شده در اینجا محاسبه می‌شوند.</p></div>{availablePositions.length ? <Button size="sm" onClick={() => onConnectAsset?.(availablePositions[0].asset)}><RiFundsLine /> اتصال دارایی</Button> : <Link href={`/investments/new?loanId=${view.loan.id ?? ""}`} className={buttonStyles({ size: "sm" })}><RiFundsLine /> اتصال دارایی</Link>}</div></CardHeader><CardContent>{availablePositions.length ? <div className="space-y-2">{availablePositions.map((position) => <div key={position.asset.id} className="rounded-2xl border p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="type-label">{position.asset.name}</div><div className="mt-1 flex flex-wrap gap-1.5"><Badge>{position.priceSourceLabel}</Badge>{!position.pricingFresh && <Badge className="border-amber-500/25 bg-amber-500/8">قیمت تازه نیست</Badge>}</div></div><div className="text-end"><SensitiveValue className="type-strong">{formatMoney(position.currentValueToman, settings.displayUnit, true)}</SensitiveValue><SensitiveValue className={cn("mt-1 block type-caption type-body-strong", position.pnlToman > 0 && "text-profit", position.pnlToman < 0 && "text-loss")}>{formatSignedMoney(position.pnlToman, settings.displayUnit, true)} · {formatPercent(position.returnPct, 1)}</SensitiveValue></div></div><div className="mt-3 grid grid-cols-2 gap-3 border-t pt-3 type-caption"><div><span className="text-muted-foreground">بهای باز: </span><SensitiveValue>{formatMoney(position.openCostToman, settings.displayUnit, true)}</SensitiveValue></div><div><span className="text-muted-foreground">معادل قسط: </span><span>{(Math.abs(position.pnlToman) / view.installmentToman).toLocaleString("fa-IR", { maximumFractionDigits: 1 })}</span></div></div>{budget > 0 && position.unrealizedPnlToman < -budget && <div className="mt-3 rounded-xl border border-destructive/25 bg-destructive/8 p-2.5 type-caption text-destructive">زیان باز این موقعیت از بودجه {view.loan.riskBudgetInstallments?.toLocaleString("fa-IR")} قسط عبور کرده است. این عبور از بودجه در تب ریسک پایش می‌شود و بعد از برگشت معنی‌دار دوباره آماده هشدار خواهد شد.</div>}</div>)}</div> : <div className="rounded-2xl border border-dashed p-6 text-center"><RiFundsLine className="mx-auto size-6 text-primary"/><div className="mt-2 type-strong">هنوز دارایی‌ای به این وام متصل نشده است</div><p className="mt-1 type-caption leading-6 text-muted-foreground">برای شروع، روی «اتصال دارایی» بزن.</p></div>}</CardContent></Card>
  {view.loan.allocationPlan?.length ? <Card><CardHeader><CardTitle>برنامه تخصیص اولیه</CardTitle></CardHeader><CardContent className="space-y-2">{view.loan.allocationPlan.map((item, index) => <div key={`${item.assetId ?? "cash"}-${index}`} className="flex items-center justify-between rounded-xl border px-3 py-2"><span className="type-label">{item.label}</span><SensitiveValue className="type-strong">{formatMoney(item.amountToman, settings.displayUnit, true)}</SensitiveValue></div>)}</CardContent></Card> : null}</div>;
}
