"use client";

import { useMemo, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SensitiveValue } from "@/components/ui/sensitive-value";
import { formatMoney, formatNumber, formatPercent, formatSignedMoney, toPersianDate } from "@/lib/format";
import { buildLoanIntelligence } from "@/lib/loans/intelligence";
import type { LoanView } from "@/lib/loans/analytics";
import type { AppSettings, Asset, IncomeEvent, InvestmentTransaction } from "@/lib/types";
import { cn } from "@/lib/utils";

export function LoanIntelligencePanel({ view, settings, incomes, transactions, assets, onConnectAsset }: { view: LoanView; settings: AppSettings; incomes: IncomeEvent[]; transactions: InvestmentTransaction[]; assets: Asset[]; onConnectAsset?: (asset: Asset) => void }) {
  const intelligence = useMemo(() => buildLoanIntelligence({ view, settings, incomes, transactions }), [incomes, settings, transactions, view]);
  const [shock, setShock] = useState(-30);
  const hasAvailableAsset = view.positions.some((position) => position.status === "available");
  const hasUnavailableAsset = view.positions.some((position) => position.status === "unavailable");
  const shockedValue = hasAvailableAsset ? Math.max(0, intelligence.assetValueToman * (1 + shock / 100)) : null;
  const shockEffect = shockedValue === null ? null : shockedValue - intelligence.assetValueToman;
  const connectAction = assets[0] ? <button type="button" className="font-bold text-primary underline underline-offset-4" onClick={() => onConnectAsset?.(assets[0])}>اتصال دارایی</button> : <a className="font-bold text-primary underline underline-offset-4" href={`/investments/new?loanId=${view.loan.id ?? ""}`}>اتصال دارایی</a>;
  return <div className="space-y-4">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Stat label="کل بازپرداخت" value={formatMoney(intelligence.totalRepaymentToman, settings.displayUnit, true)} />
      <Stat label="هزینه تأمین مالی" value={formatMoney(intelligence.financingCostToman, settings.displayUnit, true)} tone="loss" />
      <Stat label="ارزش فعلی دارایی" value={hasAvailableAsset ? formatMoney(intelligence.assetValueToman, settings.displayUnit, true) : hasUnavailableAsset ? "قیمت فعلی دارایی دریافت نشده است" : "دارایی متصل نشده است"} />
      <Stat label="بازده دارایی متصل" value={intelligence.assetReturnPct === null ? "داده کافی نیست" : formatSignedPercent(intelligence.assetReturnPct)} tone={intelligence.assetReturnPct === null ? undefined : intelligence.assetReturnPct >= 0 ? "profit" : "loss"} />
    </div>
    <Card><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle>عملکرد دارایی‌های متصل</CardTitle>{connectAction}</div><p className="mt-1 type-caption text-muted-foreground">ارزش‌گذاری بر اساس قیمت معتبر بازار یا قیمت دستی ثبت‌شده است.</p></CardHeader><CardContent className="space-y-3">{hasAvailableAsset ? view.positions.filter((position) => position.status === "available").map((position) => <div key={position.asset.id} className="grid gap-2 rounded-2xl border p-3 sm:grid-cols-[1.4fr_repeat(3,1fr)] sm:items-center"><div><div className="type-strong">{position.asset.name}</div><div className="mt-1 type-caption text-muted-foreground">{position.priceSourceLabel}{position.quoteAsOf ? ` · ${toPersianDate(position.quoteAsOf)}` : ""}</div></div><MetricLine label="بهای اولیه" value={formatMoney(position.openCostToman, settings.displayUnit, true)} /><MetricLine label="ارزش امروز" value={formatMoney(position.currentValueToman, settings.displayUnit, true)} /><MetricLine label="بازده" value={formatSignedPercent(position.returnPct)} tone={position.pnlToman >= 0 ? "profit" : "loss"} /></div>) : <div className="type-caption text-muted-foreground">{hasUnavailableAsset ? "قیمت فعلی دارایی دریافت نشده است." : <>هنوز دارایی‌ای به این وام متصل نشده است. برای شروع {connectAction}.</>}</div>}</CardContent></Card>
    <Card><CardHeader><CardTitle>امتیاز سلامت وام</CardTitle><p className="mt-1 type-caption text-muted-foreground">این امتیاز بر اساس نسبت قسط، ذخیره، پوشش دارایی و وضعیت پرداخت محاسبه شده است.</p></CardHeader><CardContent><div className="flex flex-wrap items-end justify-between gap-4"><div><SensitiveValue className={cn("text-4xl font-bold", intelligence.healthLevel === "healthy" ? "text-profit" : intelligence.healthLevel === "watch" ? "text-amber-600" : "text-loss")}>{formatNumber(intelligence.healthScore)} از {formatNumber(100)}</SensitiveValue><div className="mt-2 type-body">{intelligence.healthLevel === "healthy" ? "مناسب" : intelligence.healthLevel === "watch" ? "نیازمند توجه" : "بحرانی"}</div></div><div className="grid grid-cols-2 gap-3 text-end type-caption"><div><div className="text-muted-foreground">نسبت قسط به درآمد</div><strong>{intelligence.installmentToIncomePct === null ? "نامشخص" : formatPercent(intelligence.installmentToIncomePct, 1)}</strong></div><div><div className="text-muted-foreground">پوشش بدهی با دارایی</div><strong>{hasAvailableAsset ? formatPercent(intelligence.debtCoveragePct, 0) : "قیمت معتبر موجود نیست"}</strong></div></div></div><div className="mt-4 space-y-2 type-caption"><div>{view.reserveRunwayMonths >= view.loan.reserveTargetMonths ? "✓ ذخیره اقساط کافی" : "⚠ ذخیره اقساط نیازمند تقویت"}</div><div>{!view.overdue ? "✓ پرداخت منظم" : "⚠ قسط سررسیدشده پرداخت نشده است"}</div><div>{hasAvailableAsset ? "✓ دارایی متصل با قیمت معتبر" : "⚠ دارایی متصل معتبر وجود ندارد"}</div></div></CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card><CardHeader><CardTitle>وام در برابر سرمایه‌گذاری</CardTitle><p className="mt-1 type-caption text-muted-foreground">سناریوها برای مقایسه تصمیم هستند و پیش‌بینی بازار نیستند.</p></CardHeader><CardContent className="space-y-3">{hasAvailableAsset ? <><Scenario label="نگهداری نقد" value={intelligence.cashScenarioValueToman} unit={settings.displayUnit} /><Scenario label="سرمایه‌گذاری" value={intelligence.investmentScenarioValueToman} unit={settings.displayUnit} /><Scenario label="اثر سرمایه‌گذاری نسبت به نقد" value={intelligence.investmentScenarioPnlToman} unit={settings.displayUnit} signed /></> : <div className="type-caption text-muted-foreground">برای مقایسه سرمایه‌گذاری، ابتدا یک دارایی متصل کنید.</div>}<Scenario label="صرفه‌جویی بهره در تسویه زودتر" value={intelligence.earlyRepaymentInterestSavingToman} unit={settings.displayUnit} /></CardContent></Card>
      <Card><CardHeader><CardTitle>شبیه‌سازی شوک بازار</CardTitle><p className="mt-1 type-caption text-muted-foreground">فقط روی دارایی متصل با قیمت معتبر اعمال می‌شود.</p></CardHeader><CardContent>{hasAvailableAsset ? <><div className="flex flex-wrap gap-2">{[-10, -20, -30, -50].map((value) => <button key={value} type="button" className={cn("rounded-xl border px-3 py-2 type-caption", shock === value && "border-primary bg-primary/10 text-primary")} onClick={() => setShock(value)}>افت {formatNumber(Math.abs(value))}٪</button>)}</div><div className="mt-4 grid grid-cols-2 gap-3"><Scenario label="اثر روی دارایی" value={shockEffect!} unit={settings.displayUnit} signed /><Scenario label="تغییر ارزش" value={shockedValue!} unit={settings.displayUnit} /></div><div className="mt-3 type-caption text-muted-foreground">سناریوی ترکیبی: {formatNumber(intelligence.shocks.length)} دارایی، اثر {formatSignedMoney(intelligence.combinedShockToman, settings.displayUnit, true)}</div></> : <div className="type-caption text-muted-foreground">برای اجرای شبیه‌سازی بازار، ابتدا یک دارایی متصل کنید.</div>}</CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle>قالب‌های تخصیص پیشنهادی</CardTitle><p className="mt-1 type-caption text-muted-foreground">این قالب‌ها برای مقایسه‌اند، نه توصیه قطعی مالی.</p></CardHeader><CardContent className="grid gap-3 md:grid-cols-3">{intelligence.templates.map((template) => <div key={template.id} className="rounded-2xl border p-3"><div className="type-strong">{template.title}</div><p className="mt-1 type-caption text-muted-foreground">{template.description}</p><div className="mt-3 space-y-1 type-caption">{template.rows.map((row) => <div key={row.kind} className="flex justify-between"><span>{row.label}</span><strong>{row.percent.toLocaleString("fa-IR")}٪</strong></div>)}</div></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>روند زمانی وام</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-5">{intelligence.timeline.map((event) => <div key={event.key} className="relative rounded-2xl border p-3"><div className={cn("size-2 rounded-full", event.status === "complete" ? "bg-primary" : event.status === "current" ? "bg-amber-500" : event.status === "blocked" ? "bg-destructive" : "bg-muted-foreground/40")} /><div className="mt-2 type-strong">{event.label}</div><div className="mt-1 type-caption text-muted-foreground">{toPersianDate(event.date)}</div><div className="mt-2 type-caption text-muted-foreground">{event.detail}</div></div>)}</div></CardContent></Card>
  </div>;
}

function Stat({ label, value, tone }: { label: string; value: string; tone?: "profit" | "loss" }) { return <Card><CardContent className="p-4"><div className="type-caption text-muted-foreground">{label}</div><SensitiveValue className={cn("mt-2 block type-card-title", tone === "profit" && "text-profit", tone === "loss" && "text-loss")}>{value}</SensitiveValue></CardContent></Card>; }
function Scenario({ label, value, unit, signed = false }: { label: string; value: number; unit: AppSettings["displayUnit"]; signed?: boolean }) { return <div className="flex items-center justify-between gap-3 border-b pb-2 last:border-0 last:pb-0"><span className="type-caption text-muted-foreground">{label}</span><SensitiveValue className={cn("type-strong", signed && value >= 0 ? "text-profit" : signed && "text-loss")}>{signed ? formatSignedMoney(value, unit, true) : formatMoney(value, unit, true)}</SensitiveValue></div>; }
function formatSignedPercent(value: number) { return `${value >= 0 ? "+" : ""}${formatPercent(value, 1)}`; }
function MetricLine({ label, value, tone }: { label: string; value: string; tone?: "profit" | "loss" }) { return <div><div className="type-caption text-muted-foreground">{label}</div><SensitiveValue className={cn("mt-1 block type-strong", tone === "profit" && "text-profit", tone === "loss" && "text-loss")}>{value}</SensitiveValue></div>; }
